// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: internal/logic/proto/logic.proto

package logic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2CMsg_Kind int32

const (
	C2CMsg_NONE          C2CMsg_Kind = 0
	C2CMsg_REQ_C_SRV     C2CMsg_Kind = 1
	C2CMsg_REQ_SYN_SRV_C C2CMsg_Kind = 2
	C2CMsg_REQ_SRV_C     C2CMsg_Kind = 3
)

// Enum value maps for C2CMsg_Kind.
var (
	C2CMsg_Kind_name = map[int32]string{
		0: "NONE",
		1: "REQ_C_SRV",
		2: "REQ_SYN_SRV_C",
		3: "REQ_SRV_C",
	}
	C2CMsg_Kind_value = map[string]int32{
		"NONE":          0,
		"REQ_C_SRV":     1,
		"REQ_SYN_SRV_C": 2,
		"REQ_SRV_C":     3,
	}
)

func (x C2CMsg_Kind) Enum() *C2CMsg_Kind {
	p := new(C2CMsg_Kind)
	*p = x
	return p
}

func (x C2CMsg_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (C2CMsg_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_logic_proto_logic_proto_enumTypes[0].Descriptor()
}

func (C2CMsg_Kind) Type() protoreflect.EnumType {
	return &file_internal_logic_proto_logic_proto_enumTypes[0]
}

func (x C2CMsg_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use C2CMsg_Kind.Descriptor instead.
func (C2CMsg_Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_logic_proto_logic_proto_rawDescGZIP(), []int{0, 0}
}

type C2CMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind C2CMsg_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=logic.C2CMsg_Kind" json:"kind,omitempty"`
	// Types that are assignable to UserId:
	//
	//	*C2CMsg_From
	//	*C2CMsg_To
	UserId isC2CMsg_UserId `protobuf_oneof:"user_id"`
	MsgId  uint64          `protobuf:"varint,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Data   *anypb.Any      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *C2CMsg) Reset() {
	*x = C2CMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_logic_proto_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2CMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CMsg) ProtoMessage() {}

func (x *C2CMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_logic_proto_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CMsg.ProtoReflect.Descriptor instead.
func (*C2CMsg) Descriptor() ([]byte, []int) {
	return file_internal_logic_proto_logic_proto_rawDescGZIP(), []int{0}
}

func (x *C2CMsg) GetKind() C2CMsg_Kind {
	if x != nil {
		return x.Kind
	}
	return C2CMsg_NONE
}

func (m *C2CMsg) GetUserId() isC2CMsg_UserId {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (x *C2CMsg) GetFrom() uint64 {
	if x, ok := x.GetUserId().(*C2CMsg_From); ok {
		return x.From
	}
	return 0
}

func (x *C2CMsg) GetTo() uint64 {
	if x, ok := x.GetUserId().(*C2CMsg_To); ok {
		return x.To
	}
	return 0
}

func (x *C2CMsg) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *C2CMsg) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type isC2CMsg_UserId interface {
	isC2CMsg_UserId()
}

type C2CMsg_From struct {
	From uint64 `protobuf:"varint,2,opt,name=from,proto3,oneof"`
}

type C2CMsg_To struct {
	To uint64 `protobuf:"varint,3,opt,name=to,proto3,oneof"`
}

func (*C2CMsg_From) isC2CMsg_UserId() {}

func (*C2CMsg_To) isC2CMsg_UserId() {}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UserId:
	//
	//	*Ack_From
	//	*Ack_To
	UserId isAck_UserId `protobuf_oneof:"user_id"`
	MsgId  uint64       `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_logic_proto_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_logic_proto_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_logic_proto_logic_proto_rawDescGZIP(), []int{1}
}

func (m *Ack) GetUserId() isAck_UserId {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (x *Ack) GetFrom() uint64 {
	if x, ok := x.GetUserId().(*Ack_From); ok {
		return x.From
	}
	return 0
}

func (x *Ack) GetTo() uint64 {
	if x, ok := x.GetUserId().(*Ack_To); ok {
		return x.To
	}
	return 0
}

func (x *Ack) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type isAck_UserId interface {
	isAck_UserId()
}

type Ack_From struct {
	From uint64 `protobuf:"varint,1,opt,name=from,proto3,oneof"`
}

type Ack_To struct {
	To uint64 `protobuf:"varint,2,opt,name=to,proto3,oneof"`
}

func (*Ack_From) isAck_UserId() {}

func (*Ack_To) isAck_UserId() {}

var File_internal_logic_proto_logic_proto protoreflect.FileDescriptor

var file_internal_logic_proto_logic_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x06, 0x43, 0x32, 0x43, 0x4d, 0x73, 0x67, 0x12,
	0x26, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x43, 0x32, 0x43, 0x4d, 0x73, 0x67, 0x2e, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x10, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x74, 0x6f, 0x12,
	0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x41, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x51, 0x5f, 0x43, 0x5f, 0x53, 0x52, 0x56, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x51, 0x5f, 0x53, 0x59, 0x4e, 0x5f, 0x53, 0x52, 0x56,
	0x5f, 0x43, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x51, 0x5f, 0x53, 0x52, 0x56, 0x5f,
	0x43, 0x10, 0x03, 0x42, 0x09, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22, 0x4f,
	0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x15, 0x0a,
	0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6d,
	0x73, 0x67, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x42,
	0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x64,
	0x78, 0x6a, 0x2f, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2d, 0x77, 0x61, 0x67, 0x6f, 0x6e, 0x2f, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_logic_proto_logic_proto_rawDescOnce sync.Once
	file_internal_logic_proto_logic_proto_rawDescData = file_internal_logic_proto_logic_proto_rawDesc
)

func file_internal_logic_proto_logic_proto_rawDescGZIP() []byte {
	file_internal_logic_proto_logic_proto_rawDescOnce.Do(func() {
		file_internal_logic_proto_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_logic_proto_logic_proto_rawDescData)
	})
	return file_internal_logic_proto_logic_proto_rawDescData
}

var file_internal_logic_proto_logic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_logic_proto_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_logic_proto_logic_proto_goTypes = []interface{}{
	(C2CMsg_Kind)(0),  // 0: logic.C2CMsg.Kind
	(*C2CMsg)(nil),    // 1: logic.C2CMsg
	(*Ack)(nil),       // 2: logic.Ack
	(*anypb.Any)(nil), // 3: google.protobuf.Any
}
var file_internal_logic_proto_logic_proto_depIdxs = []int32{
	0, // 0: logic.C2CMsg.kind:type_name -> logic.C2CMsg.Kind
	3, // 1: logic.C2CMsg.data:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_logic_proto_logic_proto_init() }
func file_internal_logic_proto_logic_proto_init() {
	if File_internal_logic_proto_logic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_logic_proto_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2CMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_logic_proto_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_logic_proto_logic_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*C2CMsg_From)(nil),
		(*C2CMsg_To)(nil),
	}
	file_internal_logic_proto_logic_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Ack_From)(nil),
		(*Ack_To)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_logic_proto_logic_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_logic_proto_logic_proto_goTypes,
		DependencyIndexes: file_internal_logic_proto_logic_proto_depIdxs,
		EnumInfos:         file_internal_logic_proto_logic_proto_enumTypes,
		MessageInfos:      file_internal_logic_proto_logic_proto_msgTypes,
	}.Build()
	File_internal_logic_proto_logic_proto = out.File
	file_internal_logic_proto_logic_proto_rawDesc = nil
	file_internal_logic_proto_logic_proto_goTypes = nil
	file_internal_logic_proto_logic_proto_depIdxs = nil
}
